// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrbknkrkhyoobkpdyaay.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpyYmtua3JraHlvb2JrcGR5YWF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ4NTEwOTgsImV4cCI6MjA4MDQyNzA5OH0.zVFxv6mVGGKX6dYHx2ixMdeEgTcuh8GgsJ0pErGtHH0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});